//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coloretto.Actions
{
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ActionResult", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Actions")]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.Coloretto.ColorettoCard))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.Coloretto.ColorettoCardTypes))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.Coloretto.ColorettoCardColors))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.Coloretto.ColorettoCard[][]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.Coloretto.ColorettoCard[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.DeckOfColorettoCard18sfr_SrW))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.DeckDeckNodeOfColorettoCardColorettoCardCr971jc2))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.Card))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Actions.BaseAction[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Actions.BaseAction))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Actions.ActionResult[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Game.ColorettoGame))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Game.TurnActions))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Game.TurnActions[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Game.GameStates))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Player.Profile))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Player.ProfileCategory))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Player.Profile[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Services.Data.GameInfo[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Coloretto.Services.Data.GameInfo))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ColorettoServerLibrary.GameStates))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(bool[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Actions.BaseAction>))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Actions.ActionResult>))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ReadOnlyCollection<System.Collections.ObjectModel.ReadOnlyCollection<CardManagement.Coloretto.ColorettoCard[]>>))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ReadOnlyCollection<CardManagement.Coloretto.ColorettoCard[]>[]))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ReadOnlyCollection<CardManagement.Coloretto.ColorettoCard[]>))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Game.TurnActions>))]
	public partial class ActionResult : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string _actionField;

		private object _dataField;

		private Coloretto.Game.ColorettoGame _gameField;

		private Coloretto.Player.Profile _playerField;

		private bool _successField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string _action
		{
			get
			{
				return this._actionField;
			}
			set
			{
				this._actionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public object _data
		{
			get
			{
				return this._dataField;
			}
			set
			{
				this._dataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Coloretto.Game.ColorettoGame _game
		{
			get
			{
				return this._gameField;
			}
			set
			{
				this._gameField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Coloretto.Player.Profile _player
		{
			get
			{
				return this._playerField;
			}
			set
			{
				this._playerField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public bool _success
		{
			get
			{
				return this._successField;
			}
			set
			{
				this._successField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "BaseAction", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Actions")]
	public partial class BaseAction : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string _nameField;

		private System.Guid _uniqueIdField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string _name
		{
			get
			{
				return this._nameField;
			}
			set
			{
				this._nameField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Guid _uniqueId
		{
			get
			{
				return this._uniqueIdField;
			}
			set
			{
				this._uniqueIdField = value;
			}
		}
	}
}
namespace Coloretto.Game
{
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ColorettoGame", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Game")]
	public partial class ColorettoGame : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private int _currentPlayerIndexField;

		private Coloretto.Game.TurnActions _currentTurnField;

		private int _cycleField;

		private CardManagement.DeckOfColorettoCard18sfr_SrW _deckField;

		private bool[] _doneWithCycleField;

		private System.Collections.ObjectModel.ReadOnlyCollection<System.Collections.ObjectModel.ReadOnlyCollection<CardManagement.Coloretto.ColorettoCard[]>> _gameScoresField;

		private CardManagement.Coloretto.ColorettoCard[][] _handsField;

		private System.Guid _idField;

		private bool _isLastCycleForRoundField;

		private int _numberOfRoundsField;

		private CardManagement.Coloretto.ColorettoCard[][] _pilesField;

		private Coloretto.Player.Profile[] _playersField;

		private System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Game.TurnActions> _previousTurnsField;

		private int _roundField;

		private Coloretto.Game.GameStates _stateField;

		private int _turnField;

		private CardManagement.Coloretto.ColorettoCard _visibleCardField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _currentPlayerIndex
		{
			get
			{
				return this._currentPlayerIndexField;
			}
			set
			{
				this._currentPlayerIndexField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Coloretto.Game.TurnActions _currentTurn
		{
			get
			{
				return this._currentTurnField;
			}
			set
			{
				this._currentTurnField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _cycle
		{
			get
			{
				return this._cycleField;
			}
			set
			{
				this._cycleField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public CardManagement.DeckOfColorettoCard18sfr_SrW _deck
		{
			get
			{
				return this._deckField;
			}
			set
			{
				this._deckField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public bool[] _doneWithCycle
		{
			get
			{
				return this._doneWithCycleField;
			}
			set
			{
				this._doneWithCycleField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Collections.ObjectModel.ReadOnlyCollection<System.Collections.ObjectModel.ReadOnlyCollection<CardManagement.Coloretto.ColorettoCard[]>> _gameScores
		{
			get
			{
				return this._gameScoresField;
			}
			set
			{
				this._gameScoresField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public CardManagement.Coloretto.ColorettoCard[][] _hands
		{
			get
			{
				return this._handsField;
			}
			set
			{
				this._handsField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Guid _id
		{
			get
			{
				return this._idField;
			}
			set
			{
				this._idField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public bool _isLastCycleForRound
		{
			get
			{
				return this._isLastCycleForRoundField;
			}
			set
			{
				this._isLastCycleForRoundField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _numberOfRounds
		{
			get
			{
				return this._numberOfRoundsField;
			}
			set
			{
				this._numberOfRoundsField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public CardManagement.Coloretto.ColorettoCard[][] _piles
		{
			get
			{
				return this._pilesField;
			}
			set
			{
				this._pilesField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Coloretto.Player.Profile[] _players
		{
			get
			{
				return this._playersField;
			}
			set
			{
				this._playersField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Game.TurnActions> _previousTurns
		{
			get
			{
				return this._previousTurnsField;
			}
			set
			{
				this._previousTurnsField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _round
		{
			get
			{
				return this._roundField;
			}
			set
			{
				this._roundField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Coloretto.Game.GameStates _state
		{
			get
			{
				return this._stateField;
			}
			set
			{
				this._stateField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _turn
		{
			get
			{
				return this._turnField;
			}
			set
			{
				this._turnField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public CardManagement.Coloretto.ColorettoCard _visibleCard
		{
			get
			{
				return this._visibleCardField;
			}
			set
			{
				this._visibleCardField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "TurnActions", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Game")]
	public partial class TurnActions : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Actions.BaseAction> _actionsField;

		private int _cycleField;

		private Coloretto.Player.Profile _playerField;

		private System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Actions.ActionResult> _resultsField;

		private int _roundField;

		private int _turnField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Actions.BaseAction> _actions
		{
			get
			{
				return this._actionsField;
			}
			set
			{
				this._actionsField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _cycle
		{
			get
			{
				return this._cycleField;
			}
			set
			{
				this._cycleField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Coloretto.Player.Profile _player
		{
			get
			{
				return this._playerField;
			}
			set
			{
				this._playerField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Collections.ObjectModel.ReadOnlyCollection<Coloretto.Actions.ActionResult> _results
		{
			get
			{
				return this._resultsField;
			}
			set
			{
				this._resultsField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _round
		{
			get
			{
				return this._roundField;
			}
			set
			{
				this._roundField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _turn
		{
			get
			{
				return this._turnField;
			}
			set
			{
				this._turnField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "GameStates", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Game")]
	public enum GameStates : int
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Finished = 2,
	}
}
namespace Coloretto.Player
{
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "Profile", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Player")]
	public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private Coloretto.Player.ProfileCategory _categoryField;

		private string _colorField;

		private System.Guid _uniqueIdField;

		private string _usernameField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public Coloretto.Player.ProfileCategory _category
		{
			get
			{
				return this._categoryField;
			}
			set
			{
				this._categoryField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string _color
		{
			get
			{
				return this._colorField;
			}
			set
			{
				this._colorField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Guid _uniqueId
		{
			get
			{
				return this._uniqueIdField;
			}
			set
			{
				this._uniqueIdField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string _username
		{
			get
			{
				return this._usernameField;
			}
			set
			{
				this._usernameField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ProfileCategory", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Player")]
	public partial class ProfileCategory : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private System.Guid _idField;

		private string _nameField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Guid _id
		{
			get
			{
				return this._idField;
			}
			set
			{
				this._idField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string _name
		{
			get
			{
				return this._nameField;
			}
			set
			{
				this._nameField = value;
			}
		}
	}
}
namespace CardManagement.Coloretto
{
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ColorettoCard", Namespace = "http://schemas.datacontract.org/2004/07/CardManagement.Coloretto")]
	public partial class ColorettoCard : CardManagement.Card
	{

		private CardManagement.Coloretto.ColorettoCardTypes CardTypek__BackingFieldField;

		private CardManagement.Coloretto.ColorettoCardColors Colork__BackingFieldField;

		private System.Nullable<int> FixedDeckPositionk__BackingFieldField;

		[System.Runtime.Serialization.DataMemberAttribute(Name = "<CardType>k__BackingField", IsRequired = true)]
		public CardManagement.Coloretto.ColorettoCardTypes CardTypek__BackingField
		{
			get
			{
				return this.CardTypek__BackingFieldField;
			}
			set
			{
				this.CardTypek__BackingFieldField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(Name = "<Color>k__BackingField", IsRequired = true)]
		public CardManagement.Coloretto.ColorettoCardColors Colork__BackingField
		{
			get
			{
				return this.Colork__BackingFieldField;
			}
			set
			{
				this.Colork__BackingFieldField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(Name = "<FixedDeckPosition>k__BackingField", IsRequired = true)]
		public System.Nullable<int> FixedDeckPositionk__BackingField
		{
			get
			{
				return this.FixedDeckPositionk__BackingFieldField;
			}
			set
			{
				this.FixedDeckPositionk__BackingFieldField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ColorettoCardTypes", Namespace = "http://schemas.datacontract.org/2004/07/CardManagement.Coloretto")]
	public enum ColorettoCardTypes : int
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Color = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Plus2 = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wild = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		LastCycle = 4,
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "ColorettoCardColors", Namespace = "http://schemas.datacontract.org/2004/07/CardManagement.Coloretto")]
	public enum ColorettoCardColors : int
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Green = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Brown = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Gray = 3,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Blue = 4,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Orange = 5,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yellow = 6,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pink = 7,
	}
}
namespace CardManagement
{
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeckOfColorettoCard18sfr_SrW", Namespace = "http://schemas.datacontract.org/2004/07/CardManagement")]
	public partial class DeckOfColorettoCard18sfr_SrW : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private CardManagement.DeckDeckNodeOfColorettoCardColorettoCardCr971jc2 _firstDeckNodeField;

		private int _originalSizeField;

		private int _sizeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public CardManagement.DeckDeckNodeOfColorettoCardColorettoCardCr971jc2 _firstDeckNode
		{
			get
			{
				return this._firstDeckNodeField;
			}
			set
			{
				this._firstDeckNodeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _originalSize
		{
			get
			{
				return this._originalSizeField;
			}
			set
			{
				this._originalSizeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public int _size
		{
			get
			{
				return this._sizeField;
			}
			set
			{
				this._sizeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "Deck.DeckNodeOfColorettoCardColorettoCardCr971jc2", Namespace = "http://schemas.datacontract.org/2004/07/CardManagement")]
	public partial class DeckDeckNodeOfColorettoCardColorettoCardCr971jc2 : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private CardManagement.Coloretto.ColorettoCard CardField;

		private CardManagement.DeckDeckNodeOfColorettoCardColorettoCardCr971jc2 NextField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public CardManagement.Coloretto.ColorettoCard Card
		{
			get
			{
				return this.CardField;
			}
			set
			{
				this.CardField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public CardManagement.DeckDeckNodeOfColorettoCardColorettoCardCr971jc2 Next
		{
			get
			{
				return this.NextField;
			}
			set
			{
				this.NextField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "Card", Namespace = "http://schemas.datacontract.org/2004/07/CardManagement")]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CardManagement.Coloretto.ColorettoCard))]
	public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private System.Guid _idField;

		private string _nameField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public System.Guid _id
		{
			get
			{
				return this._idField;
			}
			set
			{
				this._idField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
		public string _name
		{
			get
			{
				return this._nameField;
			}
			set
			{
				this._nameField = value;
			}
		}
	}
}
namespace Coloretto.Services.Data
{
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "GameInfo", Namespace = "http://schemas.datacontract.org/2004/07/Coloretto.Services.Data")]
	public partial class GameInfo : object, System.Runtime.Serialization.IExtensibleDataObject
	{

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private System.DateTime CreationField;

		private string GameIdField;

		private string OwnerField;

		private string[] PlayersField;

		private ColorettoServerLibrary.GameStates StateField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public System.DateTime Creation
		{
			get
			{
				return this.CreationField;
			}
			set
			{
				this.CreationField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string GameId
		{
			get
			{
				return this.GameIdField;
			}
			set
			{
				this.GameIdField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Owner
		{
			get
			{
				return this.OwnerField;
			}
			set
			{
				this.OwnerField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string[] Players
		{
			get
			{
				return this.PlayersField;
			}
			set
			{
				this.PlayersField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public ColorettoServerLibrary.GameStates State
		{
			get
			{
				return this.StateField;
			}
			set
			{
				this.StateField = value;
			}
		}
	}
}
namespace ColorettoServerLibrary
{
	using System.Runtime.Serialization;


	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "GameStates", Namespace = "http://schemas.datacontract.org/2004/07/ColorettoServerLibrary")]
	public enum GameStates : int
	{

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 0,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Created = 1,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 2,

		[System.Runtime.Serialization.EnumMemberAttribute()]
		Finished = 3,
	}
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IColorettoService")]
public interface IColorettoService
{

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IColorettoService/HelloWorld", ReplyAction = "http://tempuri.org/IColorettoService/HelloWorldResponse")]
	string HelloWorld();

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IColorettoService/CreateGame", ReplyAction = "http://tempuri.org/IColorettoService/CreateGameResponse")]
	string CreateGame();

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IColorettoService/DrawCard", ReplyAction = "http://tempuri.org/IColorettoService/DrawCardResponse")]
	Coloretto.Actions.ActionResult DrawCard(int pileNumber);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IColorettoService/GetMyGames", ReplyAction = "http://tempuri.org/IColorettoService/GetMyGamesResponse")]
	Coloretto.Services.Data.GameInfo[] GetMyGames();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IColorettoServiceChannel : IColorettoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ColorettoServiceClient : System.ServiceModel.ClientBase<IColorettoService>, IColorettoService
{

	public ColorettoServiceClient()
	{
	}

	public ColorettoServiceClient(string endpointConfigurationName) :
		base(endpointConfigurationName)
	{
	}

	public ColorettoServiceClient(string endpointConfigurationName, string remoteAddress) :
		base(endpointConfigurationName, remoteAddress)
	{
	}

	public ColorettoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
		base(endpointConfigurationName, remoteAddress)
	{
	}

	public ColorettoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
		base(binding, remoteAddress)
	{
	}

	public string HelloWorld()
	{
		return base.Channel.HelloWorld();
	}

	public string CreateGame()
	{
		return base.Channel.CreateGame();
	}

	public Coloretto.Actions.ActionResult DrawCard(int pileNumber)
	{
		return base.Channel.DrawCard(pileNumber);
	}

	public Coloretto.Services.Data.GameInfo[] GetMyGames()
	{
		return base.Channel.GetMyGames();
	}
}
